In [1]:
from sklearn import svm,datasets
iris = datasets.load_iris()

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(iris.data,columns=iris.feature_names)
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df[47:52]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
47                4.6               3.2                1.4               0.2   
48                5.3               3.7                1.5               0.2   
49                5.0               3.3                1.4               0.2   
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   

        flower  
47      setosa  
48      setosa  
49      setosa  
50  versicolor  
51  versicolor

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train,X_test,y_train,y_test = train_test_split(iris.data, iris.target, test_size=0.2)

In [6]:
model = svm.SVC(kernel='rbf',C=30,gamma='auto')
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.9666666666666667

In [7]:
from sklearn.model_selection import cross_val_score

In [8]:
cross_val_score(svm.SVC(kernel='rbf',C=30,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.9       , 0.93333333, 1.        ])

In [9]:
cross_val_score(svm.SVC(kernel='linear',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [10]:
cross_val_score(svm.SVC(kernel='rbf',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [11]:
import numpy as np

In [13]:
kernels =['rbf','linear']
c = [1,10,20,50]
avg_score = {}

for kval in kernels:
    for cval in c:
        cv_scores = cross_val_score(svm.SVC(kernel=kval,C=cval,gamma='auto'),iris.data,iris.target,cv=5)
        avg_score[kval + '_' + str(cval)] = np.average(cv_scores)
        
avg_score

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'rbf_50': 0.96,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666,
 'linear_50': 0.9666666666666666}

In [15]:
from sklearn.model_selection import GridSearchCV

In [17]:
clf = GridSearchCV(svm.SVC(gamma='auto'), {
    'C': [1,10,20,50],
    'kernel': ['rbf','linear']}
    , cv=5, return_train_score=False)

In [18]:
clf.fit(iris.data,iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00165591, 0.0008019 , 0.00084696, 0.00071216, 0.00078154,
        0.00060558, 0.00065002, 0.00052061]),
 'std_fit_time': array([5.47536551e-04, 1.27903122e-04, 1.32568071e-04, 6.57895322e-05,
        6.18321934e-05, 4.20582808e-05, 1.78190416e-05, 1.85486590e-05]),
 'mean_score_time': array([0.000878  , 0.00040326, 0.00040603, 0.000354  , 0.0004055 ,
        0.00029221, 0.00032883, 0.00025082]),
 'std_score_time': array([1.99459940e-04, 6.98065171e-05, 5.69980990e-05, 2.55111890e-05,
        3.82123030e-05, 1.34232836e-05, 1.08833838e-05, 6.14916598e-06]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 50, 50],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_valu

In [21]:
df_results = pd.DataFrame(clf.cv_results_)
df_results

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.001656      0.000548         0.000878        0.000199       1   
1       0.000802      0.000128         0.000403        0.000070       1   
2       0.000847      0.000133         0.000406        0.000057      10   
3       0.000712      0.000066         0.000354        0.000026      10   
4       0.000782      0.000062         0.000406        0.000038      20   
5       0.000606      0.000042         0.000292        0.000013      20   
6       0.000650      0.000018         0.000329        0.000011      50   
7       0.000521      0.000019         0.000251        0.000006      50   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   
6          rbf     {'C': 50, 'kernel': 'rbf'}           1.000000   
7       linear  {'C': 50, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           1.000000           0.966667           0.966667                1.0   
1           1.000000           0.966667           0.966667                1.0   
2           1.000000           0.966667           0.966667                1.0   
3           1.000000           0.900000           0.966667                1.0   
4           1.000000           0.900000           0.966667                1.0   
5           1.000000           0.900000           0.933333                1.0   
6           0.966667           0.900000           0.933333                1.0   
7           1.000000           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6  
6         0.960000        0.038873                8  
7         0.966667        0.042164                6

In [24]:
df_results[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667
6      50          rbf         0.960000
7      50       linear         0.966667

In [25]:
clf.best_score_

0.9800000000000001

In [26]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_validate_data',
 '_validate_params',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'inverse_transform',
 'multimetric_',
 'n_fe

In [27]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [28]:
# This tells us that we get the best scores when the value of C is 1 and the kernel is rbf.